### ISSUE TITLE
Complete settings tab

### ISSUE THREAD

**Issue by henhuy** [rl-institut/digiplan#229]
- [x] add sliders and switches from excel to base Json file
- [x] add logic
- [x] change main-slider-value-change JS functions based on detail settings
- [x] add future scenario & correct start values
- [ ] add texts with dynamically changing values depending on slider setting
- [x] proof on concept for taking slider values from digipipe json instead of base json 
- [x] add potential areas on switch click on map
- [ ] what happens with colored bar?

**Comment by nesnoj** [comment]
> * add sliders and switches from excel to base Json file
> * [x]  add logic
> * [x]  change main-slider-value-change JS functions based on detail settings
> * [x]  add future scenario & correct start values
> * [ ]  add texts with dynamically changing values depending on slider setting

Texts have been updated and remain static.

> * [x]  proof on concept for taking slider values from digipipe json instead of base json
> * [x]  add potential areas on switch click on map
> * [ ]  what happens with colored bar?

Will be kept as it is.
