### ISSUE TITLE
Read default wind capacity from datapackage

### ISSUE THREAD

**Issue by henhuy** [rl-institut/digiplan#314]
Hey @nesnoj,

I want to implement wind turbines results for 2045.
What default system size shall I use for wind turbines (aka default capacity net). Could not find it in datapackage...

**Comment by nesnoj** [comment]
Done in https://github.com/rl-institut/digipipe/commit/fad950d4e881cc6fee962cedfcae4edab67cacb8
Data in now available in the latest datapackage [2023-08-31](https://wolke.rl-institut.de/f/512057) in `/datapackage/data/scalars/technology_data.json` -> "nominal_power_per_unit"

**Comment by nesnoj** [comment]
Value included in datapackage

**Comment by nesnoj** [comment]
Was done in 32da8f5
