### ISSUE TITLE
Fix all translations

### ISSUE THREAD

**Issue by henhuy** [rl-institut/digiplan#326]
Default language is german.
All text occurances have to be checked.
At first `makemessages` and compilemessages` have to be run in order to see all missing places.

**Comment by nesnoj** [comment]
Places with EN or empty texts have now been listed [here](https://wolke.rl-institut.de/f/505769) by @aaronschilling

**Comment by josihoppe** [comment]
> Places with EN or empty texts have now been listed [here](https://wolke.rl-institut.de/f/505769) by @aaronschilling

thanks for the list! Helped a lot! 

I just did not know, what to do about missing texts.
