### ISSUE TITLE
App content does not fit into viewport even in full HD

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/digiplan#355]
We got feedback from 2 users that the content does not fit into their viewport. Reported problems:
- [ ] Only small space left for the map
- [ ] Detail settings for technology not vertically scrollable (no scrollbar)
- [ ] Layer menu right not vertically scrollable (no scrollbar)
- [ ] Popups are truncated (known flaw)

It's unknown whether this is related to the browser or user settings. I cannot reproduce by changing the zoom level.
_________________
**Example 1** (1920x1080, latest Firefox v117):
![example1](https://github.com/rl-institut/digiplan/assets/15910173/e3d3864e-a941-4d8f-87a4-de85d31bc4b0)

_________________
**Example 2** (1280x1024, Firefox 117):
![example2](https://github.com/rl-institut/digiplan/assets/15910173/3d122ddd-4946-4ab6-82e1-695183a5518d)

_________________
**Expected** (Chrome Linux v103)
![image](https://github.com/rl-institut/digiplan/assets/15910173/6f60a619-eea7-4679-b87b-bc3025adc5cf)

**Comment by bmlancien** [comment]
Right now I cannot say what's the issue, no. I checked again on Firefox on my smaller screen and this is working...

**Comment by nesnoj** [comment]
Additions
- The 2nd example has a too small resolution
- The scrollbar appears on hover which is the default behavior in FF
- I tested on Win with FF v118 and everything works fine

I'll add a note on technical requirements to the onboarding.
