### ISSUE TITLE
Region chart and choropleth legend visible when going back to region today

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/digiplan#390]
When going back from settings to region today, the region chart is still visible and the dropdown is selected but the choropleth is not shown. Also, the choropleth legend is still visible.

**Comment by henhuy** [comment]
I see two options:
1. Deselect dropdown option and hide region chart when going to settings.
2. Reactivate choropleth of selected option from before
What do you prefer?

**Comment by nesnoj** [comment]
> I see two options:
> 
> 1. Deselect dropdown option and hide region chart when going to settings.
> 2. Reactivate choropleth of selected option from before
> 
> What do you prefer?

Yes, thanks. I quickly implemented 1 but I'd prefer 2. Is 2. possible (to retain selection) even when the user visited the results in between?
So [region today (choro is selected)] -> [settings] -> [results (a different choro is selected)] -> [settings] -> [region today (previously selected choro is shown again)]
If this is more complicated, I'll add 1.

**Comment by henhuy** [comment]
I think, selected option is still selected and only hidden - so this should be as simple as (pseudo code):
subscribe to TODAY_MENU_SELECTED -> function reactivate choropleth -> activate selected option

**Comment by nesnoj** [comment]
Fixed in #392
